# Generated by Django 4.1.3 on 2022-11-14 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.DateTimeField()),
                ('lessonNum', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('interval', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)])),
                ('topic', models.CharField(max_length=50)),
                ('teacher', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
