# Generated by Django 4.1.3 on 2022-11-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonrequest_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.student'),
        ),
    ]
